export default {
  LOGINSCREEN: 'LoginScreen',
  SIGNUPSCREEN: 'SignUpScreen',
  HOMESCREEN: 'HomeScreen',
  FORGOTPASSWORDSCREEN: 'ForgotPasswordScreen',
  DISCOVERSCREEN: 'DiscoverScreen',
  MYPDFSAVEDSCREEN: 'MyPdfSavedScreen',
  MYPDFSCREEN: 'MyPdfScreen',
  BOTTOMTABNAVIGATION: 'BottomTabNavigation',
  DRAWERNAVIGATION: 'DrawerNavigation',
  BOTHSTACKNAVIGATION: 'BothStackNavigation',
  COURSESCREEN: 'CourseScreen',
  SYLLABUSSCREEN: 'SyllabusScreen',
  BOOKSCREEN: 'BookScreen',
  PAPERSOLUTIONSCREEN: 'PaperSolutionScreen',
  OLDPAPERSCREEN: 'OldPaperScreen',
  IMPMATERIALSCREEN: 'ImpMaterialScreen',
  PDFVIEWERSCREEN: 'PdfViewerScreen',
};
